imports:
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret: "%SECRET%"
    router:
        resource: "%kernel.root_dir%/config/routing_%kernel.environment%.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    # csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    # templating:
    #     engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   %kernel.root_dir%/../var/sessions/%kernel.environment%
    fragments:       ~
    http_method_override: true
    assets: ~
    profiler: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        url: %DSN_URL%
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

#Monolog Configuration
monolog:
    handlers:
        main:
            type:  stream
            path:  "php://output"
            level: "%LOG_LEVEL%"

# Swiftmailer Configuration
# swiftmailer:
#     transport: "%MAILER_TRANSPORT%"
#     host:      "%MAILER_HOST%"
#     username:  "%MAILER_USER%"
#     password:  "%MAILER_PASSWORD%"
#     spool:     { type: memory }